<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE CATALOG [
 <!ELEMENT CATALOG (PRODUCT+)>
 <!ELEMENT PRODUCT (SPECIFICATIONS+, PRICE+, NOTES?)>
 <!ATTLIST PRODUCT NAME CDATA #REQUIRED>
 <!ELEMENT SPECIFICATIONS (#PCDATA)>
 <!ATTLIST SPECIFICATIONS SIZE CDATA #REQUIRED
 COLOR CDATA #REQUIRED>
 <!ELEMENT PRICE (#PCDATA)>
 <!ATTLIST PRICE WHOLESALE NMTOKEN #REQUIRED
  RETAIL NMTOKEN #REQUIRED
  SALES.TAX NMTOKEN #IMPLIED
  SHIPPING NMTOKEN #REQUIRED>
 <!ELEMENT NOTES (#PCDATA)>
] >
<CATALOG>
 <PRODUCT NAME="T-shirt">
   <SPECIFICATIONS SIZE="XL" COLOR="WHITE"></SPECIFICATIONS>
   <PRICE WHOLESALE="9.95" RETAIL="19.95" SALES.TAX="2.56" SHIPPING="5.00"></PRICE>
   <NOTES>Dilbert</NOTES>
 </PRODUCT>
 <PRODUCT NAME="Shirt">
   <SPECIFICATIONS SIZE="38" COLOR="BLACK"></SPECIFICATIONS>
   <PRICE WHOLESALE="69.95" RETAIL="79.95" SALES.TAX="4.54" SHIPPING="10.00">
     Euro</PRICE>
 </PRODUCT>
</CATALOG>
